### ISSUE TITLE
Can't load videos

### ISSUE THREAD

**Issue by maio2002** [scottpetrovic/animator-video-reference#1]
Hi,
first of all thanks for your contribution. This is something I really need in Krita to do animation.

So, when I select a video (.mp4), the export-button stays gray and there is also no thumbnail.
Furthermore, I get this error window if I change something:
![Screenshot (477)](https://user-images.githubusercontent.com/13366782/56985596-fca66b80-6b88-11e9-8892-66fc6f3cda00.png)

I have also FFMPEG installed. (I'm able to render my animation.)

Yours sincerely,
Maio

**Comment by scottpetrovic** [comment]
When you installed ffmpeg, it should also have another file in it called "ffprobe" in the same bin folder, that is what is used to read the file and populate the dialog with all the info. Is that there?

I probably need to mention that in the readme. Let me know if that fixes it.

It also might have to do that it cannot find those programs from the command line (which this plugin is doing). If you open a command line window, type "ffmpeg --version". It should say what version of ffmpeg you have. If that isn't working, it means you need to add the ffmpeg bin folder location to your environment variables. How to do that here (https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/). I put mine here "C:\ffmpeg\bin\"

**Comment by maio2002** [comment]
Hi,
Thanks for answering!
I've set the path for ffmpeg and I'm now able to load my videos. 
But I get an error when I try to export them:
![Screenshot (479)](https://user-images.githubusercontent.com/13366782/57012128-4c2a7d00-6c05-11e9-917c-829c860e6d16.png)

Some details:
When I type the command "ffmpeg --version" I get an error. (However "ffmpeg -version" and "ffmpeg" does work :D) 
![cmd](https://user-images.githubusercontent.com/13366782/57012706-19ce4f00-6c08-11e9-97b8-00d11d861f5e.PNG)

I have python 3.6.6 (set as standard) and Krita 4.17.

**Comment by scottpetrovic** [comment]
ahhh, you need to upgrade your Krita version to Krita 4.2 to get the new animation API calls. It technically isn't out yet, but you can get a nightly build (that is pretty stable) .

https://binary-factory.kde.org/job/Krita_Nightly_Windows_Build/
In the artifacts area, the second zip file is the installer version, and the third link is the portable version (don't need to install the portable version, it is all self-contained in a folder).

**Comment by maio2002** [comment]
Yep, that was the problem.
Thank you :)

**Comment by scottpetrovic** [comment]
as an FYI for anyone else that might come here later with similar issues. I just added some checking in the plugin to sniff out any of this stuff you might be missing. The UI will be disabled and the plugin will give you instructions on what you need to do get it working.

I probably need to add something similar later if the video fails to load for whatever reason.
