### ISSUE TITLE
Does not work Krita 5.0.0 Beta: "You need Krita 4.2 or newer"

### ISSUE THREAD

**Issue by ilegacy** [scottpetrovic/animator-video-reference#15]
Hi,

I'm running Krita 5.0.0-Beta and it seems that the Plugin is not compatible with this version as it complains I should use Krita 4.2 or newer.

![image](https://user-images.githubusercontent.com/12360416/133969965-f628ec9f-2c0e-48f4-8034-b9a0dc0e9aeb.png)

Have a nice day!
Simon

**Comment by scottpetrovic** [comment]
hi. Thanks for the feedback. I am going to be abandoning this plugin. Another developer wanted to convert this code to C++ and build it right into Krita. If you look at the release notes for 5.0, this functionality is added in there. If there is a problem with it, it is part of a bug in Krita core now. https://krita.org/en/krita-5-0-release-notes/  Search for "Import Videos" to quickly find it

As of this writing 5.0 is still in beta, so the release notes will slowly be updated up until 5.0 is actually released.

**Comment by ilegacy** [comment]
Oh, that's a positive surprise! Thank you for the information. You're right, there is actually an "Import Video" Button. Super cool! <3 have agreat day!
